# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\charl\source\repos\crgrove\automated-drone-image-analysis-tool\resources/views/algorithms/ThermalRange.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ThermalRange(object):
    def setupUi(self, ThermalRange):
        ThermalRange.setObjectName("ThermalRange")
        ThermalRange.resize(674, 94)
        self.verticalLayout = QtWidgets.QVBoxLayout(ThermalRange)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minTempLabel = QtWidgets.QLabel(ThermalRange)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minTempLabel.setFont(font)
        self.minTempLabel.setObjectName("minTempLabel")
        self.horizontalLayout_3.addWidget(self.minTempLabel)
        self.minTempSpinBox = QtWidgets.QSpinBox(ThermalRange)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minTempSpinBox.setFont(font)
        self.minTempSpinBox.setMinimum(-30)
        self.minTempSpinBox.setMaximum(50)
        self.minTempSpinBox.setProperty("value", 35)
        self.minTempSpinBox.setObjectName("minTempSpinBox")
        self.horizontalLayout_3.addWidget(self.minTempSpinBox)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.maxTempLabel = QtWidgets.QLabel(ThermalRange)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxTempLabel.setFont(font)
        self.maxTempLabel.setObjectName("maxTempLabel")
        self.horizontalLayout_3.addWidget(self.maxTempLabel)
        self.maxTempSpinBox = QtWidgets.QSpinBox(ThermalRange)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxTempSpinBox.setFont(font)
        self.maxTempSpinBox.setMinimum(-30)
        self.maxTempSpinBox.setMaximum(93)
        self.maxTempSpinBox.setProperty("value", 40)
        self.maxTempSpinBox.setObjectName("maxTempSpinBox")
        self.horizontalLayout_3.addWidget(self.maxTempSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.colorMapLabel = QtWidgets.QLabel(ThermalRange)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorMapLabel.setFont(font)
        self.colorMapLabel.setObjectName("colorMapLabel")
        self.horizontalLayout_3.addWidget(self.colorMapLabel)
        self.colorMapComboBox = QtWidgets.QComboBox(ThermalRange)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorMapComboBox.setFont(font)
        self.colorMapComboBox.setObjectName("colorMapComboBox")
        self.colorMapComboBox.addItem("")
        self.colorMapComboBox.addItem("")
        self.colorMapComboBox.addItem("")
        self.colorMapComboBox.addItem("")
        self.colorMapComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.colorMapComboBox)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(ThermalRange)
        QtCore.QMetaObject.connectSlotsByName(ThermalRange)

    def retranslateUi(self, ThermalRange):
        _translate = QtCore.QCoreApplication.translate
        ThermalRange.setWindowTitle(_translate("ThermalRange", "Form"))
        self.minTempLabel.setText(_translate("ThermalRange", "Minimum Temp (°C)"))
        self.maxTempLabel.setText(_translate("ThermalRange", "Maximum Temp (°C)"))
        self.colorMapLabel.setText(_translate("ThermalRange", "Color Map: "))
        self.colorMapComboBox.setItemText(0, _translate("ThermalRange", "White Hot"))
        self.colorMapComboBox.setItemText(1, _translate("ThermalRange", "Black Hot"))
        self.colorMapComboBox.setItemText(2, _translate("ThermalRange", "Inferno (Iron Red)"))
        self.colorMapComboBox.setItemText(3, _translate("ThermalRange", "Hot (Fulgurite)"))
        self.colorMapComboBox.setItemText(4, _translate("ThermalRange", "Jet (Rainbow2)"))
