# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\charl\source\repos\crgrove\automated-drone-image-analysis-tool\resources/views/algorithms/RXAnomaly.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RXAnomaly(object):
    def setupUi(self, RXAnomaly):
        RXAnomaly.setObjectName("RXAnomaly")
        RXAnomaly.resize(674, 94)
        self.verticalLayout = QtWidgets.QVBoxLayout(RXAnomaly)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sensitivityLabel = QtWidgets.QLabel(RXAnomaly)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sensitivityLabel.setFont(font)
        self.sensitivityLabel.setObjectName("sensitivityLabel")
        self.horizontalLayout_3.addWidget(self.sensitivityLabel)
        self.sensitivitySlider = QtWidgets.QSlider(RXAnomaly)
        self.sensitivitySlider.setMinimum(1)
        self.sensitivitySlider.setMaximum(10)
        self.sensitivitySlider.setPageStep(1)
        self.sensitivitySlider.setProperty("value", 5)
        self.sensitivitySlider.setSliderPosition(5)
        self.sensitivitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.sensitivitySlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sensitivitySlider.setTickInterval(1)
        self.sensitivitySlider.setObjectName("sensitivitySlider")
        self.horizontalLayout_3.addWidget(self.sensitivitySlider)
        self.sensitivityValueLabel = QtWidgets.QLabel(RXAnomaly)
        self.sensitivityValueLabel.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sensitivityValueLabel.setFont(font)
        self.sensitivityValueLabel.setObjectName("sensitivityValueLabel")
        self.horizontalLayout_3.addWidget(self.sensitivityValueLabel)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(RXAnomaly)
        QtCore.QMetaObject.connectSlotsByName(RXAnomaly)

    def retranslateUi(self, RXAnomaly):
        _translate = QtCore.QCoreApplication.translate
        RXAnomaly.setWindowTitle(_translate("RXAnomaly", "Form"))
        self.sensitivityLabel.setText(_translate("RXAnomaly", "Sensitivity:"))
        self.sensitivityValueLabel.setText(_translate("RXAnomaly", "5"))
