# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\charl\source\repos\crgrove\automated-drone-image-analysis-tool\resources/views/algorithms/RXAnomaly.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RXAnomaly(object):
    def setupUi(self, RXAnomaly):
        RXAnomaly.setObjectName("RXAnomaly")
        RXAnomaly.resize(674, 94)
        self.verticalLayout = QtWidgets.QVBoxLayout(RXAnomaly)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.segmentsLabel = QtWidgets.QLabel(RXAnomaly)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.segmentsLabel.setFont(font)
        self.segmentsLabel.setObjectName("segmentsLabel")
        self.horizontalLayout_3.addWidget(self.segmentsLabel)
        self.segmentsComboBox = QtWidgets.QComboBox(RXAnomaly)
        self.segmentsComboBox.setMinimumSize(QtCore.QSize(30, 0))
        self.segmentsComboBox.setObjectName("segmentsComboBox")
        self.segmentsComboBox.addItem("")
        self.segmentsComboBox.addItem("")
        self.segmentsComboBox.addItem("")
        self.segmentsComboBox.addItem("")
        self.segmentsComboBox.addItem("")
        self.segmentsComboBox.addItem("")
        self.segmentsComboBox.addItem("")
        self.segmentsComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.segmentsComboBox)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.sensitivityLabel = QtWidgets.QLabel(RXAnomaly)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sensitivityLabel.setFont(font)
        self.sensitivityLabel.setObjectName("sensitivityLabel")
        self.horizontalLayout_3.addWidget(self.sensitivityLabel)
        self.sensitivitySlider = QtWidgets.QSlider(RXAnomaly)
        self.sensitivitySlider.setMinimum(1)
        self.sensitivitySlider.setMaximum(10)
        self.sensitivitySlider.setPageStep(1)
        self.sensitivitySlider.setProperty("value", 5)
        self.sensitivitySlider.setSliderPosition(5)
        self.sensitivitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.sensitivitySlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sensitivitySlider.setTickInterval(1)
        self.sensitivitySlider.setObjectName("sensitivitySlider")
        self.horizontalLayout_3.addWidget(self.sensitivitySlider)
        self.sensitivityValueLabel = QtWidgets.QLabel(RXAnomaly)
        self.sensitivityValueLabel.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sensitivityValueLabel.setFont(font)
        self.sensitivityValueLabel.setObjectName("sensitivityValueLabel")
        self.horizontalLayout_3.addWidget(self.sensitivityValueLabel)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.segmentsWidget = QtWidgets.QWidget(RXAnomaly)
        self.segmentsWidget.setObjectName("segmentsWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.segmentsWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addWidget(self.segmentsWidget)

        self.retranslateUi(RXAnomaly)
        QtCore.QMetaObject.connectSlotsByName(RXAnomaly)

    def retranslateUi(self, RXAnomaly):
        _translate = QtCore.QCoreApplication.translate
        RXAnomaly.setWindowTitle(_translate("RXAnomaly", "Form"))
        self.segmentsLabel.setText(_translate("RXAnomaly", "Image Segments:"))
        self.segmentsComboBox.setItemText(0, _translate("RXAnomaly", "1"))
        self.segmentsComboBox.setItemText(1, _translate("RXAnomaly", "2"))
        self.segmentsComboBox.setItemText(2, _translate("RXAnomaly", "4"))
        self.segmentsComboBox.setItemText(3, _translate("RXAnomaly", "6"))
        self.segmentsComboBox.setItemText(4, _translate("RXAnomaly", "9"))
        self.segmentsComboBox.setItemText(5, _translate("RXAnomaly", "16"))
        self.segmentsComboBox.setItemText(6, _translate("RXAnomaly", "25"))
        self.segmentsComboBox.setItemText(7, _translate("RXAnomaly", "36"))
        self.sensitivityLabel.setText(_translate("RXAnomaly", "Sensitivity:"))
        self.sensitivityValueLabel.setText(_translate("RXAnomaly", "5"))
