# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RTMPMotionDetectionViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PySide6 import QtCore, QtGui, QtWidgets


class Ui_RTMPMotionDetectionViewer(object):
    def setupUi(self, RTMPMotionDetectionViewer):
        RTMPMotionDetectionViewer.setObjectName("RTMPMotionDetectionViewer")
        RTMPMotionDetectionViewer.resize(1400, 900)
        RTMPMotionDetectionViewer.setWindowTitle("Real-Time Motion Detection")
        
        # Central widget
        self.centralwidget = QtWidgets.QWidget(RTMPMotionDetectionViewer)
        self.centralwidget.setObjectName("centralwidget")
        
        # Main layout
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        
        # Left panel - Video display
        self.leftPanel = QtWidgets.QWidget(self.centralwidget)
        self.leftPanel.setObjectName("leftPanel")
        self.leftLayout = QtWidgets.QVBoxLayout(self.leftPanel)
        self.leftLayout.setObjectName("leftLayout")
        
        # Video display label
        self.videoLabel = QtWidgets.QLabel(self.leftPanel)
        self.videoLabel.setMinimumSize(QtCore.QSize(800, 600))
        self.videoLabel.setStyleSheet("background-color: black; color: white;")
        self.videoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videoLabel.setText("No Stream Connected")
        self.videoLabel.setScaledContents(False)
        self.videoLabel.setObjectName("videoLabel")
        self.leftLayout.addWidget(self.videoLabel)
        
        # Video control bar
        self.videoControlWidget = QtWidgets.QWidget(self.leftPanel)
        self.videoControlLayout = QtWidgets.QHBoxLayout(self.videoControlWidget)
        self.videoControlLayout.setObjectName("videoControlLayout")
        
        self.playPauseButton = QtWidgets.QPushButton("Play/Pause")
        self.playPauseButton.setObjectName("playPauseButton")
        self.videoControlLayout.addWidget(self.playPauseButton)
        
        self.currentTimeLabel = QtWidgets.QLabel("00:00")
        self.currentTimeLabel.setObjectName("currentTimeLabel")
        self.videoControlLayout.addWidget(self.currentTimeLabel)
        
        self.seekSlider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
        self.seekSlider.setMaximum(1000)
        self.seekSlider.setObjectName("seekSlider")
        self.videoControlLayout.addWidget(self.seekSlider)
        
        self.totalTimeLabel = QtWidgets.QLabel("00:00")
        self.totalTimeLabel.setObjectName("totalTimeLabel")
        self.videoControlLayout.addWidget(self.totalTimeLabel)
        
        self.leftLayout.addWidget(self.videoControlWidget)
        
        # Status bar at bottom
        self.statusWidget = QtWidgets.QWidget(self.leftPanel)
        self.statusLayout = QtWidgets.QHBoxLayout(self.statusWidget)
        self.statusLayout.setObjectName("statusLayout")
        
        self.statusLabel = QtWidgets.QLabel("Ready")
        self.statusLabel.setObjectName("statusLabel")
        self.statusLayout.addWidget(self.statusLabel)
        
        self.statusLayout.addStretch()
        
        self.fpsLabel = QtWidgets.QLabel("FPS: 0.0")
        self.fpsLabel.setObjectName("fpsLabel")
        self.statusLayout.addWidget(self.fpsLabel)
        
        self.processingTimeLabel = QtWidgets.QLabel("Processing: 0.0ms")
        self.processingTimeLabel.setObjectName("processingTimeLabel")
        self.statusLayout.addWidget(self.processingTimeLabel)
        
        self.leftLayout.addWidget(self.statusWidget)
        
        self.mainLayout.addWidget(self.leftPanel, 2)
        
        # Right panel - Controls
        self.rightPanel = QtWidgets.QWidget(self.centralwidget)
        self.rightPanel.setMaximumWidth(500)
        self.rightPanel.setObjectName("rightPanel")
        self.rightLayout = QtWidgets.QVBoxLayout(self.rightPanel)
        self.rightLayout.setObjectName("rightLayout")
        
        # Connection group
        self.connectionGroup = QtWidgets.QGroupBox("Stream Connection")
        self.connectionGroup.setObjectName("connectionGroup")
        self.connectionLayout = QtWidgets.QGridLayout(self.connectionGroup)
        
        self.streamTypeLabel = QtWidgets.QLabel("Stream Type:")
        self.connectionLayout.addWidget(self.streamTypeLabel, 0, 0)
        
        self.streamTypeCombo = QtWidgets.QComboBox()
        self.streamTypeCombo.setObjectName("streamTypeCombo")
        self.connectionLayout.addWidget(self.streamTypeCombo, 0, 1, 1, 2)
        
        self.streamUrlLabel = QtWidgets.QLabel("Stream URL:")
        self.connectionLayout.addWidget(self.streamUrlLabel, 1, 0)
        
        self.streamUrlEdit = QtWidgets.QLineEdit()
        self.streamUrlEdit.setObjectName("streamUrlEdit")
        self.connectionLayout.addWidget(self.streamUrlEdit, 1, 1)
        
        self.browseButton = QtWidgets.QPushButton("Browse")
        self.browseButton.setObjectName("browseButton")
        self.browseButton.setEnabled(False)
        self.connectionLayout.addWidget(self.browseButton, 1, 2)
        
        self.connectButton = QtWidgets.QPushButton("Connect")
        self.connectButton.setObjectName("connectButton")
        self.connectButton.setStyleSheet("background-color: #51cf66; font-weight: bold;")
        self.connectionLayout.addWidget(self.connectButton, 2, 0, 1, 3)
        
        self.rightLayout.addWidget(self.connectionGroup)
        
        # Detection Mode group
        self.modeGroup = QtWidgets.QGroupBox("Detection Mode")
        self.modeGroup.setObjectName("modeGroup")
        self.modeLayout = QtWidgets.QGridLayout(self.modeGroup)
        
        self.modeLabel = QtWidgets.QLabel("Mode:")
        self.modeLayout.addWidget(self.modeLabel, 0, 0)
        
        self.modeCombo = QtWidgets.QComboBox()
        self.modeCombo.setObjectName("modeCombo")
        self.modeLayout.addWidget(self.modeCombo, 0, 1)
        
        self.algorithmLabel = QtWidgets.QLabel("Algorithm:")
        self.modeLayout.addWidget(self.algorithmLabel, 1, 0)
        
        self.algorithmCombo = QtWidgets.QComboBox()
        self.algorithmCombo.setObjectName("algorithmCombo")
        self.modeLayout.addWidget(self.algorithmCombo, 1, 1)
        
        self.modeStatusLabel = QtWidgets.QLabel("Mode Status: Auto")
        self.modeStatusLabel.setObjectName("modeStatusLabel")
        self.modeLayout.addWidget(self.modeStatusLabel, 2, 0, 1, 2)
        
        self.rightLayout.addWidget(self.modeGroup)
        
        # Detection Parameters group
        self.parametersGroup = QtWidgets.QGroupBox("Detection Parameters")
        self.parametersGroup.setObjectName("parametersGroup")
        self.parametersLayout = QtWidgets.QGridLayout(self.parametersGroup)
        
        # Sensitivity slider
        self.sensitivityLabel = QtWidgets.QLabel("Sensitivity: 50%")
        self.parametersLayout.addWidget(self.sensitivityLabel, 0, 0)
        
        self.sensitivitySlider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
        self.sensitivitySlider.setMinimum(0)
        self.sensitivitySlider.setMaximum(100)
        self.sensitivitySlider.setValue(50)
        self.sensitivitySlider.setObjectName("sensitivitySlider")
        self.parametersLayout.addWidget(self.sensitivitySlider, 0, 1)
        
        # Min area
        self.minAreaLabel = QtWidgets.QLabel("Min Area:")
        self.parametersLayout.addWidget(self.minAreaLabel, 1, 0)
        
        self.minAreaSpinBox = QtWidgets.QSpinBox()
        self.minAreaSpinBox.setMinimum(10)
        self.minAreaSpinBox.setMaximum(10000)
        self.minAreaSpinBox.setValue(500)
        self.minAreaSpinBox.setObjectName("minAreaSpinBox")
        self.parametersLayout.addWidget(self.minAreaSpinBox, 1, 1)
        
        # Max area
        self.maxAreaLabel = QtWidgets.QLabel("Max Area:")
        self.parametersLayout.addWidget(self.maxAreaLabel, 2, 0)
        
        self.maxAreaSpinBox = QtWidgets.QSpinBox()
        self.maxAreaSpinBox.setMinimum(1000)
        self.maxAreaSpinBox.setMaximum(500000)
        self.maxAreaSpinBox.setValue(100000)
        self.maxAreaSpinBox.setObjectName("maxAreaSpinBox")
        self.parametersLayout.addWidget(self.maxAreaSpinBox, 2, 1)
        
        # Motion threshold
        self.thresholdLabel = QtWidgets.QLabel("Threshold:")
        self.parametersLayout.addWidget(self.thresholdLabel, 3, 0)
        
        self.thresholdSpinBox = QtWidgets.QDoubleSpinBox()
        self.thresholdSpinBox.setMinimum(0.0)
        self.thresholdSpinBox.setMaximum(100.0)
        self.thresholdSpinBox.setValue(25.0)
        self.thresholdSpinBox.setObjectName("thresholdSpinBox")
        self.parametersLayout.addWidget(self.thresholdSpinBox, 3, 1)
        
        # Compensation strength (for moving camera)
        self.compensationLabel = QtWidgets.QLabel("Compensation: 80%")
        self.parametersLayout.addWidget(self.compensationLabel, 4, 0)
        
        self.compensationSlider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
        self.compensationSlider.setMinimum(0)
        self.compensationSlider.setMaximum(100)
        self.compensationSlider.setValue(80)
        self.compensationSlider.setObjectName("compensationSlider")
        self.parametersLayout.addWidget(self.compensationSlider, 4, 1)
        
        # Processing Resolution dropdown
        self.resolutionDropdownLabel = QtWidgets.QLabel("Processing Resolution:")
        self.parametersLayout.addWidget(self.resolutionDropdownLabel, 5, 0)
        
        self.resolutionCombo = QtWidgets.QComboBox()
        self.resolutionCombo.setObjectName("resolutionCombo")
        self.parametersLayout.addWidget(self.resolutionCombo, 5, 1)
        
        self.rightLayout.addWidget(self.parametersGroup)
        
        # Visualization Options group
        self.visualizationGroup = QtWidgets.QGroupBox("Visualization")
        self.visualizationGroup.setObjectName("visualizationGroup")
        self.visualizationLayout = QtWidgets.QVBoxLayout(self.visualizationGroup)
        
        self.showVectorsCheckBox = QtWidgets.QCheckBox("Show Motion Vectors")
        self.showVectorsCheckBox.setObjectName("showVectorsCheckBox")
        self.visualizationLayout.addWidget(self.showVectorsCheckBox)
        
        self.showCameraMotionCheckBox = QtWidgets.QCheckBox("Show Camera Motion")
        self.showCameraMotionCheckBox.setObjectName("showCameraMotionCheckBox")
        self.visualizationLayout.addWidget(self.showCameraMotionCheckBox)
        
        self.showOverlayCheckBox = QtWidgets.QCheckBox("Show Detection Overlay")
        self.showOverlayCheckBox.setObjectName("showOverlayCheckBox")
        self.showOverlayCheckBox.setChecked(True)
        self.visualizationLayout.addWidget(self.showOverlayCheckBox)
        
        self.rightLayout.addWidget(self.visualizationGroup)
        
        # Statistics group
        self.statsGroup = QtWidgets.QGroupBox("Statistics")
        self.statsGroup.setObjectName("statsGroup")
        self.statsLayout = QtWidgets.QVBoxLayout(self.statsGroup)
        
        self.resolutionLabel = QtWidgets.QLabel("Resolution: -")
        self.resolutionLabel.setObjectName("resolutionLabel")
        self.statsLayout.addWidget(self.resolutionLabel)
        
        self.streamFpsLabel = QtWidgets.QLabel("Stream FPS: 0.0")
        self.streamFpsLabel.setObjectName("streamFpsLabel")
        self.statsLayout.addWidget(self.streamFpsLabel)
        
        self.detectionCountLabel = QtWidgets.QLabel("Detections: 0")
        self.detectionCountLabel.setObjectName("detectionCountLabel")
        self.statsLayout.addWidget(self.detectionCountLabel)
        
        self.cameraMotionLabel = QtWidgets.QLabel("Camera Motion: None")
        self.cameraMotionLabel.setObjectName("cameraMotionLabel")
        self.statsLayout.addWidget(self.cameraMotionLabel)
        
        self.sessionTimeLabel = QtWidgets.QLabel("Session: 00:00")
        self.sessionTimeLabel.setObjectName("sessionTimeLabel")
        self.statsLayout.addWidget(self.sessionTimeLabel)
        
        self.totalDetectionsLabel = QtWidgets.QLabel("Total Detections: 0")
        self.totalDetectionsLabel.setObjectName("totalDetectionsLabel")
        self.statsLayout.addWidget(self.totalDetectionsLabel)
        
        self.lastDetectionLabel = QtWidgets.QLabel("Last Detection: -")
        self.lastDetectionLabel.setObjectName("lastDetectionLabel")
        self.statsLayout.addWidget(self.lastDetectionLabel)
        
        self.rightLayout.addWidget(self.statsGroup)
        
        # Control buttons group
        self.controlsGroup = QtWidgets.QGroupBox("Controls")
        self.controlsGroup.setObjectName("controlsGroup")
        self.controlsLayout = QtWidgets.QGridLayout(self.controlsGroup)
        
        self.detectButton = QtWidgets.QPushButton("Stop Detection")
        self.detectButton.setObjectName("detectButton")
        self.detectButton.setStyleSheet("background-color: #ff6b6b; font-weight: bold;")
        self.controlsLayout.addWidget(self.detectButton, 0, 0, 1, 2)
        
        self.recordButton = QtWidgets.QPushButton("Start Recording")
        self.recordButton.setObjectName("recordButton")
        self.controlsLayout.addWidget(self.recordButton, 1, 0)
        
        self.snapshotButton = QtWidgets.QPushButton("Take Snapshot")
        self.snapshotButton.setObjectName("snapshotButton")
        self.controlsLayout.addWidget(self.snapshotButton, 1, 1)
        
        self.rightLayout.addWidget(self.controlsGroup)
        
        # Detection list (optional, for showing recent detections)
        self.detectionListWidget = QtWidgets.QListWidget()
        self.detectionListWidget.setObjectName("detectionListWidget")
        self.detectionListWidget.setMaximumHeight(150)
        self.rightLayout.addWidget(self.detectionListWidget)
        
        # Add stretch to push everything to top
        self.rightLayout.addStretch()
        
        self.mainLayout.addWidget(self.rightPanel, 1)
        
        RTMPMotionDetectionViewer.setCentralWidget(self.centralwidget)
        
        # Menu bar
        self.menubar = QtWidgets.QMenuBar(RTMPMotionDetectionViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 22))
        self.menubar.setObjectName("menubar")
        RTMPMotionDetectionViewer.setMenuBar(self.menubar)
        
        # Status bar
        self.statusbar = QtWidgets.QStatusBar(RTMPMotionDetectionViewer)
        self.statusbar.setObjectName("statusbar")
        RTMPMotionDetectionViewer.setStatusBar(self.statusbar)
        
        self.retranslateUi(RTMPMotionDetectionViewer)
        QtCore.QMetaObject.connectSlotsByName(RTMPMotionDetectionViewer)
    
    def retranslateUi(self, RTMPMotionDetectionViewer):
        _translate = QtCore.QCoreApplication.translate
        RTMPMotionDetectionViewer.setWindowTitle(_translate("RTMPMotionDetectionViewer", "Real-Time Motion Detection"))
        self.connectionGroup.setTitle(_translate("RTMPMotionDetectionViewer", "Stream Connection"))
        self.modeGroup.setTitle(_translate("RTMPMotionDetectionViewer", "Detection Mode"))
        self.parametersGroup.setTitle(_translate("RTMPMotionDetectionViewer", "Detection Parameters"))
        self.visualizationGroup.setTitle(_translate("RTMPMotionDetectionViewer", "Visualization"))
        self.statsGroup.setTitle(_translate("RTMPMotionDetectionViewer", "Statistics"))
        self.controlsGroup.setTitle(_translate("RTMPMotionDetectionViewer", "Controls"))