# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\charl\source\repos\crgrove\automated-drone-image-analysis-tool\resources/views/components\Preferences.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Preferences)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainWidget = QtWidgets.QWidget(Preferences)
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.themeWidget = QtWidgets.QWidget(self.mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.themeWidget.sizePolicy().hasHeightForWidth())
        self.themeWidget.setSizePolicy(sizePolicy)
        self.themeWidget.setObjectName("themeWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.themeWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.themeWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.themeComboBox = QtWidgets.QComboBox(self.themeWidget)
        self.themeComboBox.setObjectName("themeComboBox")
        self.themeComboBox.addItem("")
        self.themeComboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.themeComboBox)
        self.verticalLayout_2.addWidget(self.themeWidget)
        self.maxAOIsWidget = QtWidgets.QWidget(self.mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxAOIsWidget.sizePolicy().hasHeightForWidth())
        self.maxAOIsWidget.setSizePolicy(sizePolicy)
        self.maxAOIsWidget.setObjectName("maxAOIsWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.maxAOIsWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.maxAOIsLabel = QtWidgets.QLabel(self.maxAOIsWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxAOIsLabel.sizePolicy().hasHeightForWidth())
        self.maxAOIsLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxAOIsLabel.setFont(font)
        self.maxAOIsLabel.setObjectName("maxAOIsLabel")
        self.horizontalLayout_2.addWidget(self.maxAOIsLabel)
        self.maxAOIsSpinBox = QtWidgets.QSpinBox(self.maxAOIsWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxAOIsSpinBox.setFont(font)
        self.maxAOIsSpinBox.setMaximum(1000)
        self.maxAOIsSpinBox.setProperty("value", 100)
        self.maxAOIsSpinBox.setObjectName("maxAOIsSpinBox")
        self.horizontalLayout_2.addWidget(self.maxAOIsSpinBox)
        self.verticalLayout_2.addWidget(self.maxAOIsWidget)
        self.verticalLayout.addWidget(self.mainWidget, 0, QtCore.Qt.AlignTop)
        self.buttonBox = QtWidgets.QDialogButtonBox(Preferences)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Preferences)
        self.buttonBox.accepted.connect(Preferences.accept) # type: ignore
        self.buttonBox.rejected.connect(Preferences.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        _translate = QtCore.QCoreApplication.translate
        Preferences.setWindowTitle(_translate("Preferences", "Dialog"))
        self.label.setText(_translate("Preferences", "Theme:"))
        self.themeComboBox.setItemText(0, _translate("Preferences", "Light"))
        self.themeComboBox.setItemText(1, _translate("Preferences", "Dark"))
        self.maxAOIsLabel.setText(_translate("Preferences", "Max Areas of Interest: "))
