# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\xampp7\htdocs\ADIAT\resources/views\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(894, 840)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.setupFrame = QtWidgets.QFrame(self.centralwidget)
        self.setupFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.setupFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.setupFrame.setLineWidth(3)
        self.setupFrame.setObjectName("setupFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.setupFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.directoriesLayout = QtWidgets.QGridLayout()
        self.directoriesLayout.setSpacing(6)
        self.directoriesLayout.setObjectName("directoriesLayout")
        self.outputFolderLabel = QtWidgets.QLabel(self.setupFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.outputFolderLabel.setFont(font)
        self.outputFolderLabel.setObjectName("outputFolderLabel")
        self.directoriesLayout.addWidget(self.outputFolderLabel, 1, 0, 1, 1)
        self.inputFolderLine = QtWidgets.QLineEdit(self.setupFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputFolderLine.setFont(font)
        self.inputFolderLine.setObjectName("inputFolderLine")
        self.directoriesLayout.addWidget(self.inputFolderLine, 0, 1, 1, 1)
        self.inputFolderLabel = QtWidgets.QLabel(self.setupFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputFolderLabel.setFont(font)
        self.inputFolderLabel.setObjectName("inputFolderLabel")
        self.directoriesLayout.addWidget(self.inputFolderLabel, 0, 0, 1, 1)
        self.inputFolderButton = QtWidgets.QPushButton(self.setupFrame)
        self.inputFolderButton.setObjectName("inputFolderButton")
        self.directoriesLayout.addWidget(self.inputFolderButton, 0, 2, 1, 1)
        self.outputFolderLine = QtWidgets.QLineEdit(self.setupFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.outputFolderLine.setFont(font)
        self.outputFolderLine.setObjectName("outputFolderLine")
        self.directoriesLayout.addWidget(self.outputFolderLine, 1, 1, 1, 1)
        self.outputFolderButton = QtWidgets.QPushButton(self.setupFrame)
        self.outputFolderButton.setObjectName("outputFolderButton")
        self.directoriesLayout.addWidget(self.outputFolderButton, 1, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.directoriesLayout)
        self.globalOptionsLayout = QtWidgets.QHBoxLayout()
        self.globalOptionsLayout.setObjectName("globalOptionsLayout")
        self.areaLabel = QtWidgets.QLabel(self.setupFrame)
        self.areaLabel.setObjectName("areaLabel")
        self.globalOptionsLayout.addWidget(self.areaLabel)
        self.minAreaSpinBox = QtWidgets.QSpinBox(self.setupFrame)
        self.minAreaSpinBox.setMinimum(1)
        self.minAreaSpinBox.setProperty("value", 3)
        self.minAreaSpinBox.setObjectName("minAreaSpinBox")
        self.globalOptionsLayout.addWidget(self.minAreaSpinBox)
        spacerItem = QtWidgets.QSpacerItem(48, 43, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.globalOptionsLayout.addItem(spacerItem)
        self.objectColor = QtWidgets.QLabel(self.setupFrame)
        self.objectColor.setObjectName("objectColor")
        self.globalOptionsLayout.addWidget(self.objectColor)
        self.identifierColorButton = QtWidgets.QPushButton(self.setupFrame)
        self.identifierColorButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.identifierColorButton.setText("")
        self.identifierColorButton.setObjectName("identifierColorButton")
        self.globalOptionsLayout.addWidget(self.identifierColorButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.globalOptionsLayout.addItem(spacerItem1)
        self.maxThreadsLabel = QtWidgets.QLabel(self.setupFrame)
        self.maxThreadsLabel.setObjectName("maxThreadsLabel")
        self.globalOptionsLayout.addWidget(self.maxThreadsLabel)
        self.maxThreadsSpinBox = QtWidgets.QSpinBox(self.setupFrame)
        self.maxThreadsSpinBox.setMinimum(1)
        self.maxThreadsSpinBox.setMaximum(20)
        self.maxThreadsSpinBox.setProperty("value", 5)
        self.maxThreadsSpinBox.setObjectName("maxThreadsSpinBox")
        self.globalOptionsLayout.addWidget(self.maxThreadsSpinBox)
        self.verticalLayout_4.addLayout(self.globalOptionsLayout)
        self.line = QtWidgets.QFrame(self.setupFrame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.algorithmSelectorlLayout = QtWidgets.QHBoxLayout()
        self.algorithmSelectorlLayout.setObjectName("algorithmSelectorlLayout")
        self.label = QtWidgets.QLabel(self.setupFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.algorithmSelectorlLayout.addWidget(self.label)
        self.algorithmComboBox = QtWidgets.QComboBox(self.setupFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.algorithmComboBox.sizePolicy().hasHeightForWidth())
        self.algorithmComboBox.setSizePolicy(sizePolicy)
        self.algorithmComboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.algorithmComboBox.setObjectName("algorithmComboBox")
        self.algorithmComboBox.addItem("")
        self.algorithmComboBox.addItem("")
        self.algorithmSelectorlLayout.addWidget(self.algorithmComboBox)
        spacerItem2 = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.algorithmSelectorlLayout.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.algorithmSelectorlLayout)
        self.algorithmFrame = QtWidgets.QFrame(self.setupFrame)
        self.algorithmFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.algorithmFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.algorithmFrame.setLineWidth(3)
        self.algorithmFrame.setMidLineWidth(0)
        self.algorithmFrame.setObjectName("algorithmFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.algorithmFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4.addWidget(self.algorithmFrame)
        self.verticalLayout_3.addWidget(self.setupFrame)
        self.mainButtons = QtWidgets.QHBoxLayout()
        self.mainButtons.setObjectName("mainButtons")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setAutoFillBackground(False)
        self.startButton.setStyleSheet("background-color: rgb(85, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.startButton.setDefault(False)
        self.startButton.setObjectName("startButton")
        self.mainButtons.addWidget(self.startButton)
        self.viewResultsButton = QtWidgets.QPushButton(self.centralwidget)
        self.viewResultsButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewResultsButton.sizePolicy().hasHeightForWidth())
        self.viewResultsButton.setSizePolicy(sizePolicy)
        self.viewResultsButton.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.viewResultsButton.setFont(font)
        self.viewResultsButton.setAutoFillBackground(False)
        self.viewResultsButton.setStyleSheet("")
        self.viewResultsButton.setDefault(False)
        self.viewResultsButton.setObjectName("viewResultsButton")
        self.mainButtons.addWidget(self.viewResultsButton)
        spacerItem3 = QtWidgets.QSpacerItem(400, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.mainButtons.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.mainButtons)
        self.outputWindow = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.outputWindow.setReadOnly(False)
        self.outputWindow.setCenterOnScroll(True)
        self.outputWindow.setObjectName("outputWindow")
        self.verticalLayout_3.addWidget(self.outputWindow)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 894, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionLoadFile = QtWidgets.QAction(MainWindow)
        self.actionLoadFile.setObjectName("actionLoadFile")
        self.menuFile.addAction(self.actionLoadFile)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Automated Drone Image Analysis Tool - Sponsored by TEXSAR"))
        self.outputFolderLabel.setText(_translate("MainWindow", "Output Folder:"))
        self.inputFolderLabel.setText(_translate("MainWindow", "Input Folder:"))
        self.inputFolderButton.setText(_translate("MainWindow", "Select"))
        self.outputFolderButton.setText(_translate("MainWindow", "Select"))
        self.areaLabel.setText(_translate("MainWindow", "Min Object Area (px):"))
        self.objectColor.setText(_translate("MainWindow", "Object Identifer Color:"))
        self.maxThreadsLabel.setText(_translate("MainWindow", "Max Threads: "))
        self.label.setText(_translate("MainWindow", "Algorithm:"))
        self.algorithmComboBox.setItemText(0, _translate("MainWindow", "ColorMatch"))
        self.algorithmComboBox.setItemText(1, _translate("MainWindow", "ColorAnomaly"))
        self.startButton.setText(_translate("MainWindow", "Start!"))
        self.viewResultsButton.setText(_translate("MainWindow", "View Results"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoadFile.setText(_translate("MainWindow", "Open File"))


